tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "adoptopenjdk/openjdk"
tap "marcelocarlos/tap"
tap "snyk/tap"
tap "go-swagger/go-swagger"
tap "sonatype-nexus-community/nancy-tap"

# Essentials
brew "automake"
brew "bash"
brew "bash-completion"
brew "bat"
brew "binutils"
brew "cheat"
brew "cmake"
brew "colordiff"
brew "coreutils"
brew "curl"
brew "datasubst"
brew "diffutils"
brew "openssl"
brew "fd"
brew "findutils"
brew "fzf"
brew "gawk"
brew "gettext", link: true
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gnupg"
brew "grep"
brew "gzip"
brew "htop"
brew "httpie"
brew "less"
brew "mas"
brew "neovim"
brew "p7zip"
brew "pidof"
brew "pstree"
brew "readline"
brew "rsync"
brew "slackcat"
brew "screen"
brew "tcpdump"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "whois"
cask "alfred"
# cask "arq" # temporarily removed
cask "betterzip"
cask "brave-browser"
cask "caffeine"
cask "google-backup-and-sync"
cask "google-chrome"
cask "firefox"
cask "istat-menus"
cask "iterm2"
cask "osxfuse"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "spotify"
cask "steam"
cask "suspicious-package"
# cask "zoom" # zoom via brew is messy at the moment, better to install manually
cask "basictex"
mas "Magnet", id: 441258766
mas "Pastebot", id: 1179623856
mas "Slack", id: 803453959

# Dev
brew "python@3.9"
brew "gh"
brew "git"
brew "git-secrets"
brew "go"
brew "jq"
brew "markdownlint-cli", link: true
brew "node"
brew "rbenv"
brew "ruby@2.7"
brew "go-swagger"
cask "adoptopenjdk/openjdk/adoptopenjdk15"
cask "android-platform-tools"
cask "atom"
cask "postman"
# cask "insomnia"
cask "visual-studio-code"

# Ops
brew "ansible"
brew "ansible-lint"
brew "awscli"
brew "ipcalc"
brew "k9s"
brew "kubernetes-cli"
brew "kubectx"
brew "mtr"
brew "netcat"
brew "shellcheck"
brew "terraform"
cask "docker"
cask "google-cloud-sdk"

# Security
brew "conftest"
brew "opa"
brew "pinentry-mac"
brew "pwgen"
brew "nancy"
brew "nmap"
brew "semgrep"
brew "snyk"
brew "vault"
cask "apparency"
cask "little-snitch"
cask "owasp-zap"
cask "burp-suite"
mas "1Password 7", id: 1333542190

# Messaging
cask "signal"
mas "WhatsApp", id: 1147396723
